# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csuser',
            name='steam_id',
            field=models.CharField(max_length=126, null=True),
        ),
    ]
