# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_csuser_steam_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotoheteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
    ]
